### PR TITLE
Feature/EC-497-Icons fix

### LINKED ISSUE #497: Fix Icons on Input/Modal/Notification components
Having, https://github.com/stipsan/uikit-react/pull/495 merged, we can include `Icon` feature in our other components. 

- [ ] Update `Input` to have Icon.
- [ ] Update example for `Notification` to have `Icon`

### PR DESCRIPTION
**Pull request by sureshHARDIYA**
Fixes #497

### CODE REVIEW

**Comment by stipsan** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://58e1b55f-4db2-407d-945a-c01d7463798a.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/stipsan/uikit-react/branch/feature/EC-497-Icons-fix/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

File: src/Icon.js [hunk 1]
```diff
@@ -9,14 +11,15 @@ const iconNames = Object.keys(icons)
 export default class Icon extends Component {
 
   static propTypes = {
-    icon: PropTypes.oneOf(iconNames).isRequired,
-    load: PropTypes.func.isRequired,
+    icon: PropTypes.oneOf(iconNames.concat(['spinner'])).isRequired,
```
Comment (stipsan) [inline src/Icon.js]: I would change it to es6:
```
icon: PropTypes.oneOf([...iconNames, 'spinner']).isRequired,
```

File: src/Icon.js [hunk 2]
```diff
@@ -26,11 +29,15 @@ export default class Icon extends Component {
     const height = 20
     const width = 20
 
-    const { ratio, viewBox, icon, ...props } = this.props
+    const { className, ratio, viewBox, icon, ...props } = this.props
     const svg = icons[icon] && icons[icon].replace(/^<svg[^>]*>|<\/svg>$/g, '')
```
Comment (stipsan) [inline src/Icon.js]: This logic can be moved to after the `return <Spinner ...` logic to avoid checking if "spinner" exists in `icons` (we already know that it don't).

File: src/Input.js [hunk 3]
```diff
@@ -27,16 +28,13 @@ const Input = ({
...
   if (icon) {
     return (
-      <div className={cx('uk-form-icon', { 'uk-form-icon-flip': flip })}>
-        <i
-          className={cx(`uk-icon-${icon}`, {
-            'uk-icon-spin': icon === 'spinner' || icon === 'refresh',
-          })}
-        />
+      <div className="uk-inline">
+        {icon && <Icon className={cx('uk-form-icon', { 'uk-form-icon-flip': flip })} icon={icon} /> }
```
Comment (stipsan) [inline src/Input.js]: There is already a check made on line 29 to see if `icon` is truthy, it's not necessary to check it again on line 32.

File: src/Notification/NotifyMesssage.js [hunk 4]
```diff
@@ -58,9 +59,12 @@ export default class NotifyMesssage extends Component {
...
         style={{ overflow: 'hidden', transition: 'margin ease-out 300ms', ...styles[this.state.isOpen ? 1 : 0] }}
       >
-        <a className="uk-close" onClick={this.handleClose} />
+        <a className="uk-notification-close uk-close uk-icon" onClick={this.handleClose} >
+          <Icon icon="close" />
+        </a>
         <div onClick={onClick}>
-          {icon && <span><i className={`uk-icon-${icon}`} />&nbsp;</span> }
+          {icon && <Icon icon={icon} /> }
+          &nbsp;
```
Comment (stipsan) [inline src/Notification/NotifyMesssage.js]: The `&nbsp;` should only be added if there is an icon.

```js
const body = icon ? (
  <div onClick={onClick}>
    <Icon icon={icon} />
    &nbsp;
    {children}
  </div>
) : (
  <div onClick={onClick}>
    {children}
  </div>
)

  return (
      <div
        className={className}
        style={{ overflow: 'hidden', transition: 'margin ease-out 300ms', ...styles[this.state.isOpen ? 1 : 0] }}
      >
        <a className="uk-notification-close uk-close uk-icon" onClick={this.handleClose} >
          <Icon icon="close" />
        </a>
        {body}
      </div>
    )
```

File: src/__tests__/Input-test.js [hunk 5]
```diff
@@ -56,9 +56,9 @@ describe('Input', () => {
       <Input flip icon="calendar" />
     ).toJSON()).toMatchSnapshot()
 
-    expect(renderer.create(
-      <Input icon="spinner" />
-    ).toJSON()).toMatchSnapshot()
+    // expect(renderer.create(
+    //   <Input icon="spinner" />
```
Comment (stipsan) [inline src/__tests__/Input-test.js]: delete dead code

Comment (sureshHARDIYA) [inline src/__tests__/Input-test.js]: Fixed !!

File: src/Notification/NotifyMesssage.js (hunk 4 above)
Comment (sureshHARDIYA) [inline src/Notification/NotifyMesssage.js]: Fixed !!
